name: bot_dashboard
description: "Biosónica La Terapia."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  intl: ^0.20.2
  just_audio: ^0.9.46
  lottie: ^3.3.1
  marquee: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  # android: "launcher_icon"
  android: "ic_launcher"
  ios: false
  image_path: "lib/assets/images/logotipo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/images/logotipo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "lib/assets/images/logotipo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "lib/assets/images/logotipo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/lotties/
    - lib/assets/credentials.json
